#!/bin/bash

# Submits multiple jobs to the cluster, running whole-brain stats under different settings

TEST_TYPES=(state_dependence prediction_dependence decision_dependence before_reporting after_reporting)

for i in "${TEST_TYPES[@]}"
do
  echo $i
done